select 
substr(ds, 1, 10) as fecha,
application.site_id as site, 
device.platform as platform,
sum(if(jest(event_data, 'payments[0].payment_type') = 'credit_card' and application.server_poolname= 'checkout-on-mlm', CAST(jest(event_data, 'total_amount') as DOUBLE),0)) as v4_credit_card,
sum(if(jest(event_data, 'payments[0].payment_type') = 'debit_card' and application.server_poolname= 'checkout-on-mlm', CAST(jest(event_data, 'total_amount') as DOUBLE),0)) as v4_debit_card,
sum(if(jest(event_data, 'payments[0].payment_type') = 'atm' and application.server_poolname= 'checkout-on-mlm', CAST(jest(event_data, 'total_amount') as DOUBLE),0)) as v4_atm,
sum(if(jest(event_data, 'payments[0].payment_type') = 'ticket' and application.server_poolname= 'checkout-on-mlm', CAST(jest(event_data, 'total_amount') as DOUBLE),0)) as v4_ticket,
sum(if(jest(event_data, 'payments[0].payment_type') = 'prepaid_card' and application.server_poolname= 'checkout-on-mlm', CAST(jest(event_data, 'total_amount') as DOUBLE),0)) as v4_prepaid_card,
sum(if(jest(event_data, 'payments[0].payment_type') = 'account_money' and application.server_poolname= 'checkout-on-mlm', CAST(jest(event_data, 'total_amount') as DOUBLE),0)) as v4_account_money,
sum(if(jest(event_data, 'payments[0].payment_method') = 'serfin' and application.server_poolname= 'checkout-on-mlm', CAST(jest(event_data, 'total_amount') as DOUBLE),0)) as v4_serfin,
sum(if(jest(event_data, 'payments[0].payment_method') = 'amex' and application.server_poolname= 'checkout-on-mlm', CAST(jest(event_data, 'total_amount') as DOUBLE),0)) as v4_amex,
sum(if(jest(event_data, 'payments[0].payment_method') = 'mercadopagocard' and application.server_poolname= 'checkout-on-mlm', CAST(jest(event_data, 'total_amount') as DOUBLE),0)) as v4_mercadopagocard,
sum(if(jest(event_data, 'payments[0].payment_method') = 'debvisa' and application.server_poolname= 'checkout-on-mlm', CAST(jest(event_data, 'total_amount') as DOUBLE),0)) as v4_debvisa,
sum(if(jest(event_data, 'payments[0].payment_method') = 'visa' and application.server_poolname= 'checkout-on-mlm', CAST(jest(event_data, 'total_amount') as DOUBLE),0)) as v4_visa,
sum(if(jest(event_data, 'payments[0].payment_method') = 'telecomm' and application.server_poolname= 'checkout-on-mlm', CAST(jest(event_data, 'total_amount') as DOUBLE),0)) as v4_telecomm,
sum(if(jest(event_data, 'payments[0].payment_method') = 'master' and application.server_poolname= 'checkout-on-mlm', CAST(jest(event_data, 'total_amount') as DOUBLE),0)) as v4_master,
sum(if(jest(event_data, 'payments[0].payment_method') = '7eleven' and application.server_poolname= 'checkout-on-mlm', CAST(jest(event_data, 'total_amount') as DOUBLE),0)) as v4_seven_eleven,
sum(if(jest(event_data, 'payments[0].payment_method') = 'debmaster' and application.server_poolname= 'checkout-on-mlm', CAST(jest(event_data, 'total_amount') as DOUBLE),0)) as v4_debmaster,
sum(if(jest(event_data, 'payments[0].payment_method') = 'oxxo' and application.server_poolname= 'checkout-on-mlm', CAST(jest(event_data, 'total_amount') as DOUBLE),0)) as v4_oxxo,
sum(if(jest(event_data, 'payments[0].payment_method') = 'banamex' and application.server_poolname= 'checkout-on-mlm', CAST(jest(event_data, 'total_amount') as DOUBLE),0)) as v4_banamex,
sum(if(jest(event_data, 'payments[0].payment_method') = 'bancomer' and application.server_poolname= 'checkout-on-mlm', CAST(jest(event_data, 'total_amount') as DOUBLE),0)) as v4_bancomer,
sum(if(application.server_poolname= 'checkout-on-mlm', CAST(jest(event_data, 'total_amount') as DOUBLE),0)) as v4_total_amount,
sum(if(application.server_poolname= 'checkout-on-mlm', CAST(jest(event_data, 'total_amount_with_shipping') as DOUBLE),0)) as v4_total_amount_with_shipping,
sum(if(jest(event_data, 'payments[0].payment_type') = 'credit_card' and application.server_poolname= 'buyingflow-cart-web-mobile-mlm-direct', CAST(jest(event_data, 'total_amount') as DOUBLE),0)) as v5_credit_card,
sum(if(jest(event_data, 'payments[0].payment_type') = 'debit_card' and application.server_poolname= 'buyingflow-cart-web-mobile-mlm-direct', CAST(jest(event_data, 'total_amount') as DOUBLE),0)) as v5_debit_card,
sum(if(jest(event_data, 'payments[0].payment_type') = 'ticket' and application.server_poolname= 'buyingflow-cart-web-mobile-mlm-direct', CAST(jest(event_data, 'total_amount') as DOUBLE),0)) as v5_ticket,
sum(if(jest(event_data, 'payments[0].payment_type') = 'prepaid_card' and application.server_poolname= 'buyingflow-cart-web-mobile-mlm-direct', CAST(jest(event_data, 'total_amount') as DOUBLE),0)) as v5_prepaid_card,
sum(if(jest(event_data, 'payments[0].payment_type') = 'account_money' and application.server_poolname= 'buyingflow-cart-web-mobile-mlm-direct', CAST(jest(event_data, 'total_amount') as DOUBLE),0)) as v5_account_money,
sum(if(jest(event_data, 'payments[0].payment_type') = 'bank_transfer' and application.server_poolname= 'buyingflow-cart-web-mobile-mlm-direct', CAST(jest(event_data, 'total_amount') as DOUBLE),0)) as v5_bank_transfer,
sum(if(jest(event_data, 'payments[0].payment_type') = 'cash' and application.server_poolname= 'buyingflow-cart-web-mobile-mlm-direct', CAST(jest(event_data, 'total_amount') as DOUBLE),0)) as v5_bank_cash,
sum(if(jest(event_data, 'payments[0].payment_method') = 'serfin' and application.server_poolname= 'buyingflow-cart-web-mobile-mlm-direct', CAST(jest(event_data, 'total_amount') as DOUBLE),0)) as v5_serfin,
sum(if(jest(event_data, 'payments[0].payment_method') = 'amex' and application.server_poolname= 'buyingflow-cart-web-mobile-mlm-direct', CAST(jest(event_data, 'total_amount') as DOUBLE),0)) as v5_amex,
sum(if(jest(event_data, 'payments[0].payment_method') = 'mercadopagocard' and application.server_poolname= 'buyingflow-cart-web-mobile-mlm-direct', CAST(jest(event_data, 'total_amount') as DOUBLE),0)) as v5_mercadopagocard,
sum(if(jest(event_data, 'payments[0].payment_method') = 'debvisa' and application.server_poolname= 'buyingflow-cart-web-mobile-mlm-direct', CAST(jest(event_data, 'total_amount') as DOUBLE),0)) as v5_debvisa,
sum(if(jest(event_data, 'payments[0].payment_method') = 'visa' and application.server_poolname= 'buyingflow-cart-web-mobile-mlm-direct', CAST(jest(event_data, 'total_amount') as DOUBLE),0)) as v5_visa,
sum(if(jest(event_data, 'payments[0].payment_method') = 'telecomm' and application.server_poolname= 'buyingflow-cart-web-mobile-mlm-direct', CAST(jest(event_data, 'total_amount') as DOUBLE),0)) as v5_telecomm,
sum(if(jest(event_data, 'payments[0].payment_method') = 'master' and application.server_poolname= 'buyingflow-cart-web-mobile-mlm-direct', CAST(jest(event_data, 'total_amount') as DOUBLE),0)) as v5_master,
sum(if(jest(event_data, 'payments[0].payment_method') = '7eleven' and application.server_poolname= 'buyingflow-cart-web-mobile-mlm-direct', CAST(jest(event_data, 'total_amount') as DOUBLE),0)) as v5_seven_eleven,
sum(if(jest(event_data, 'payments[0].payment_method') = 'debmaster' and application.server_poolname= 'buyingflow-cart-web-mobile-mlm-direct', CAST(jest(event_data, 'total_amount') as DOUBLE),0)) as v5_debmaster,
sum(if(jest(event_data, 'payments[0].payment_method') = 'oxxo' and application.server_poolname= 'buyingflow-cart-web-mobile-mlm-direct', CAST(jest(event_data, 'total_amount') as DOUBLE),0)) as v5_oxxo,
sum(if(jest(event_data, 'payments[0].payment_method') = 'banamex' and application.server_poolname= 'buyingflow-cart-web-mobile-mlm-direct', CAST(jest(event_data, 'total_amount') as DOUBLE),0)) as v5_banamex,
sum(if(jest(event_data, 'payments[0].payment_method') = 'bancomer' and application.server_poolname= 'buyingflow-cart-web-mobile-mlm-direct', CAST(jest(event_data, 'total_amount') as DOUBLE),0)) as v5_bancomer,
sum(if(jest(event_data, 'payments[0].payment_method') = 'cash' and application.server_poolname= 'buyingflow-cart-web-mobile-mlm-direct', CAST(jest(event_data, 'total_amount') as DOUBLE),0)) as v5_cash,
sum(if(application.server_poolname= 'buyingflow-cart-web-mobile-mlm-direct', CAST(jest(event_data, 'total_amount') as DOUBLE),0)) as v5_total_amount,
sum(if(application.server_poolname= 'buyingflow-cart-web-mobile-mlm-direct', CAST(jest(event_data, 'total_amount_with_shipping') as DOUBLE),0)) as v5_total_amount_with_shipping,
sum (CAST(jest(event_data, 'total_amount') as DOUBLE)) as total_amount,
sum (CAST(jest(event_data, 'total_amount_with_shipping') as DOUBLE)) as total_amount_with_shipping
from tracks 
where 	   ds >='@param01'
and 	   ds <'@param02'
and application.site_id = 'MLM'
and path = '/checkout/congrats' 
and device.platform = '/web/mobile' 
group by substr(ds, 1, 10), application.site_id, device.platform
