select 
todo.fecha, 
todo.site, 
todo.platform,
sum(if(todo.payment_type = 'credit_card' and todo.server_poolname = 'checkout-on-mlm', todo.total_amount_usd,0)) as v4_gmv_credit_card,
sum(if(todo.payment_type = 'debit_card' and todo.server_poolname = 'checkout-on-mlm', todo.total_amount_usd,0)) as v4_gmv_debit_card,
sum(if(todo.payment_type = 'atm' and todo.server_poolname = 'checkout-on-mlm', todo.total_amount_usd,0)) as v4_gmv_atm,
sum(if(todo.payment_type = 'ticket' and todo.server_poolname = 'checkout-on-mlm', todo.total_amount_usd,0)) as v4_gmv_ticket,
sum(if(todo.payment_type = 'prepaid_card' and todo.server_poolname = 'checkout-on-mlm', todo.total_amount_usd,0)) as v4_gmv_prepaid_card,
sum(if(todo.payment_type = 'account_money' and todo.server_poolname = 'checkout-on-mlm', todo.total_amount_usd,0)) as v4_gmv_account_money,
sum(if(length(todo.payment_type) = 0 and todo.server_poolname = 'checkout-on-mlm', todo.total_amount_usd,0)) as v4_gmv_accord,
sum(if(todo.payment_method = 'serfin' and todo.server_poolname = 'checkout-on-mlm', todo.total_amount_usd,0)) as v4_gmv_serfin,
sum(if(todo.payment_method = 'amex' and todo.server_poolname = 'checkout-on-mlm', todo.total_amount_usd,0)) as v4_gmv_amex,
sum(if(todo.payment_method = 'mercadopagocard' and todo.server_poolname = 'checkout-on-mlm', todo.total_amount_usd,0)) as v4_gmv_mercadopagocard,
sum(if(todo.payment_method = 'debvisa' and todo.server_poolname = 'checkout-on-mlm', todo.total_amount_usd,0)) as v4_gmv_debvisa,
sum(if(todo.payment_method = 'visa' and todo.server_poolname = 'checkout-on-mlm', todo.total_amount_usd,0)) as v4_gmv_visa,
sum(if(todo.payment_method = 'telecomm' and todo.server_poolname = 'checkout-on-mlm', todo.total_amount_usd,0)) as v4_gmv_telecomm,
sum(if(todo.payment_method = 'master' and todo.server_poolname = 'checkout-on-mlm', todo.total_amount_usd,0)) as v4_gmv_master,
sum(if(todo.payment_method = '7eleven' and todo.server_poolname = 'checkout-on-mlm', todo.total_amount_usd,0)) as v4_gmv_seven_eleven,
sum(if(todo.payment_method = 'debmaster' and todo.server_poolname = 'checkout-on-mlm', todo.total_amount_usd,0)) as v4_gmv_debmaster,
sum(if(todo.payment_method = 'oxxo' and todo.server_poolname = 'checkout-on-mlm', todo.total_amount_usd,0)) as v4_gmv_oxxo,
sum(if(todo.payment_method = 'banamex' and todo.server_poolname = 'checkout-on-mlm', todo.total_amount_usd,0)) as v4_gmv_banamex,
sum(if(todo.payment_method = 'bancomer' and todo.server_poolname = 'checkout-on-mlm', todo.total_amount_usd,0)) as v4_gmv_bancomer,
sum(if(todo.server_poolname= 'checkout-on-mlm', todo.total_amount,0)) as v4_total_amount,
sum(if(todo.server_poolname= 'checkout-on-mlm', todo.total_amount_with_shipping,0)) as v4_total_amount_with_shipping,
sum(if(todo.server_poolname= 'checkout-on-mlm', todo.total_amount_usd,0)) as v4_total_amount_usd,
sum(if(todo.payment_type = 'credit_card' and todo.server_poolname = 'checkout-on-mlm', 1,0)) as v4_si_credit_card,
sum(if(todo.payment_type = 'debit_card' and todo.server_poolname = 'checkout-on-mlm', 1,0)) as v4_si_debit_card,
sum(if(todo.payment_type = 'atm' and todo.server_poolname = 'checkout-on-mlm', 1,0)) as v4_si_atm,
sum(if(todo.payment_type = 'ticket' and todo.server_poolname = 'checkout-on-mlm', 1,0)) as v4_si_ticket,
sum(if(todo.payment_type = 'prepaid_card' and todo.server_poolname = 'checkout-on-mlm', 1,0)) as v4_si_prepaid_card,
sum(if(todo.payment_type = 'account_money' and todo.server_poolname = 'checkout-on-mlm', 1,0)) as v4_si_account_money,
sum(if(length(todo.payment_type) = 0 and todo.server_poolname = 'checkout-on-mlm', 1,0)) as v4_si_accord,
sum(if(todo.payment_method = 'serfin' and todo.server_poolname = 'checkout-on-mlm', 1,0)) as v4_si_serfin,
sum(if(todo.payment_method = 'amex' and todo.server_poolname = 'checkout-on-mlm', 1,0)) as v4_si_amex,
sum(if(todo.payment_method = 'mercadopagocard' and todo.server_poolname = 'checkout-on-mlm', 1,0)) as v4_si_mercadopagocard,
sum(if(todo.payment_method = 'debvisa' and todo.server_poolname = 'checkout-on-mlm', 1,0)) as v4_si_debvisa,
sum(if(todo.payment_method = 'visa' and todo.server_poolname = 'checkout-on-mlm', 1,0)) as v4_si_visa,
sum(if(todo.payment_method = 'telecomm' and todo.server_poolname = 'checkout-on-mlm', 1,0)) as v4_si_telecomm,
sum(if(todo.payment_method = 'master' and todo.server_poolname = 'checkout-on-mlm', 1,0)) as v4_si_master,
sum(if(todo.payment_method = '7eleven' and todo.server_poolname = 'checkout-on-mlm', 1,0)) as v4_si_seven_eleven,
sum(if(todo.payment_method = 'debmaster' and todo.server_poolname = 'checkout-on-mlm', 1,0)) as v4_si_debmaster,
sum(if(todo.payment_method = 'oxxo' and todo.server_poolname = 'checkout-on-mlm', 1,0)) as v4_si_oxxo,
sum(if(todo.payment_method = 'banamex' and todo.server_poolname = 'checkout-on-mlm', 1,0)) as v4_si_banamex,
sum(if(todo.payment_method = 'bancomer' and todo.server_poolname = 'checkout-on-mlm', 1,0)) as v4_si_bancomer,
count(if(todo.server_poolname = 'checkout-on-mlm', 1,0)) as v4_si_total,
sum(if(todo.payment_type = 'credit_card' and todo.server_poolname = 'buyingflow-cart-web-mobile-mlm-direct', todo.total_amount_usd,0)) as v5_gmv_credit_card,
sum(if(todo.payment_type = 'debit_card' and todo.server_poolname = 'buyingflow-cart-web-mobile-mlm-direct', todo.total_amount_usd,0)) as v5_gmv_debit_card,
sum(if(todo.payment_type = 'ticket' and todo.server_poolname = 'buyingflow-cart-web-mobile-mlm-direct', todo.total_amount_usd,0)) as v5_gmv_ticket,
sum(if(todo.payment_type = 'prepaid_card' and todo.server_poolname = 'buyingflow-cart-web-mobile-mlm-direct', todo.total_amount_usd,0)) as v5_gmv_prepaid_card,
sum(if(todo.payment_type = 'account_money' and todo.server_poolname = 'buyingflow-cart-web-mobile-mlm-direct', todo.total_amount_usd,0)) as v5_gmv_account_money,
sum(if(todo.payment_type = 'bank_transfer' and todo.server_poolname = 'buyingflow-cart-web-mobile-mlm-direct', todo.total_amount_usd,0)) as v5_gmv_bank_transfer,
sum(if(todo.payment_type = 'cash' and todo.server_poolname = 'buyingflow-cart-web-mobile-mlm-direct', todo.total_amount_usd,0)) as v5_gmv_bank_cash,
sum(if(todo.payment_method = 'serfin' and todo.server_poolname = 'buyingflow-cart-web-mobile-mlm-direct', todo.total_amount_usd,0)) as v5_gmv_serfin,
sum(if(todo.payment_method = 'amex' and todo.server_poolname = 'buyingflow-cart-web-mobile-mlm-direct', todo.total_amount_usd,0)) as v5_gmv_amex,
sum(if(todo.payment_method = 'mercadopagocard' and todo.server_poolname = 'buyingflow-cart-web-mobile-mlm-direct', todo.total_amount_usd,0)) as v5_gmv_mercadopagocard,
sum(if(todo.payment_method = 'debvisa' and todo.server_poolname = 'buyingflow-cart-web-mobile-mlm-direct', todo.total_amount_usd,0)) as v5_gmv_debvisa,
sum(if(todo.payment_method = 'visa' and todo.server_poolname = 'buyingflow-cart-web-mobile-mlm-direct', todo.total_amount_usd,0)) as v5_gmv_visa,
sum(if(todo.payment_method = 'telecomm' and todo.server_poolname = 'buyingflow-cart-web-mobile-mlm-direct', todo.total_amount_usd,0)) as v5_gmv_telecomm,
sum(if(todo.payment_method = 'master' and todo.server_poolname = 'buyingflow-cart-web-mobile-mlm-direct', todo.total_amount_usd,0)) as v5_gmv_master,
sum(if(todo.payment_method = '7eleven' and todo.server_poolname = 'buyingflow-cart-web-mobile-mlm-direct', todo.total_amount_usd,0)) as v5_gmv_seven_eleven,
sum(if(todo.payment_method = 'debmaster' and todo.server_poolname = 'buyingflow-cart-web-mobile-mlm-direct', todo.total_amount_usd,0)) as v5_gmv_debmaster,
sum(if(todo.payment_method = 'oxxo' and todo.server_poolname = 'buyingflow-cart-web-mobile-mlm-direct', todo.total_amount_usd,0)) as v5_gmv_oxxo,
sum(if(todo.payment_method = 'banamex' and todo.server_poolname = 'buyingflow-cart-web-mobile-mlm-direct', todo.total_amount_usd,0)) as v5_gmv_banamex,
sum(if(todo.payment_method = 'bancomer' and todo.server_poolname = 'buyingflow-cart-web-mobile-mlm-direct', todo.total_amount_usd,0)) as v5_gmv_bancomer,
sum(if(todo.payment_method = 'banamex' and todo.payment_type = 'bank_transfer' and todo.server_poolname = 'buyingflow-cart-web-mobile-mlm-direct', todo.total_amount_usd,0)) as v5_gmv_banamex_bank_transfer,
sum(if(todo.payment_method = 'bancomer' and todo.payment_type = 'bank_transfer' and todo.server_poolname = 'buyingflow-cart-web-mobile-mlm-direct', todo.total_amount_usd,0)) as v5_gmv_bancomer_bank_transfer,
sum(if(todo.payment_method = 'serfin' and todo.payment_type = 'bank_transfer' and todo.server_poolname = 'buyingflow-cart-web-mobile-mlm-direct', todo.total_amount_usd,0)) as v5_gmv_serfin_bank_transfer,
sum(if(todo.payment_method = 'banamex' and todo.payment_type = 'ticket' and todo.server_poolname = 'buyingflow-cart-web-mobile-mlm-direct', todo.total_amount_usd,0)) as v5_gmv_banamex_ticket,
sum(if(todo.payment_method = 'bancomer' and todo.payment_type = 'ticket' and todo.server_poolname = 'buyingflow-cart-web-mobile-mlm-direct', todo.total_amount_usd,0)) as v5_gmv_bancomer_ticket,
sum(if(todo.payment_method = 'serfin' and todo.payment_type = 'ticket' and todo.server_poolname = 'buyingflow-cart-web-mobile-mlm-direct', todo.total_amount_usd,0)) as v5_gmv_serfin_ticket,
sum(if(todo.server_poolname = 'buyingflow-cart-web-mobile-mlm-direct', todo.total_amount,0)) as v5_total_amount,
sum(if(todo.server_poolname = 'buyingflow-cart-web-mobile-mlm-direct', todo.total_amount_with_shipping,0)) as v5_total_amount_with_shipping,
sum(if(todo.server_poolname = 'buyingflow-cart-web-mobile-mlm-direct', todo.total_amount_usd,0)) as v5_total_amount_usd,
sum(if(todo.payment_type = 'credit_card' and todo.server_poolname = 'buyingflow-cart-web-mobile-mlm-direct', 1,0)) as v5_si_credit_card,
sum(if(todo.payment_type = 'debit_card' and todo.server_poolname = 'buyingflow-cart-web-mobile-mlm-direct', 1,0)) as v5_si_debit_card,
sum(if(todo.payment_type = 'ticket' and todo.server_poolname = 'buyingflow-cart-web-mobile-mlm-direct', 1,0)) as v5_si_ticket,
sum(if(todo.payment_type = 'prepaid_card' and todo.server_poolname = 'buyingflow-cart-web-mobile-mlm-direct', 1,0)) as v5_si_prepaid_card,
sum(if(todo.payment_type = 'account_money' and todo.server_poolname = 'buyingflow-cart-web-mobile-mlm-direct', 1,0)) as v5_si_account_money,
sum(if(todo.payment_type = 'bank_transfer' and todo.server_poolname = 'buyingflow-cart-web-mobile-mlm-direct', 1,0)) as v5_si_bank_transfer,
sum(if(todo.payment_type = 'cash' and todo.server_poolname = 'buyingflow-cart-web-mobile-mlm-direct', 1,0)) as v5_si_bank_cash,
sum(if(todo.payment_method = 'serfin' and todo.server_poolname = 'buyingflow-cart-web-mobile-mlm-direct', 1,0)) as v5_si_serfin,
sum(if(todo.payment_method = 'amex' and todo.server_poolname = 'buyingflow-cart-web-mobile-mlm-direct', 1,0)) as v5_si_amex,
sum(if(todo.payment_method = 'mercadopagocard' and todo.server_poolname = 'buyingflow-cart-web-mobile-mlm-direct', 1,0)) as v5_si_mercadopagocard,
sum(if(todo.payment_method = 'debvisa' and todo.server_poolname = 'buyingflow-cart-web-mobile-mlm-direct', 1,0)) as v5_si_debvisa,
sum(if(todo.payment_method = 'visa' and todo.server_poolname = 'buyingflow-cart-web-mobile-mlm-direct', 1,0)) as v5_si_visa,
sum(if(todo.payment_method = 'telecomm' and todo.server_poolname = 'buyingflow-cart-web-mobile-mlm-direct', 1,0)) as v5_si_telecomm,
sum(if(todo.payment_method = 'master' and todo.server_poolname = 'buyingflow-cart-web-mobile-mlm-direct', 1,0)) as v5_si_master,
sum(if(todo.payment_method = '7eleven' and todo.server_poolname = 'buyingflow-cart-web-mobile-mlm-direct', 1,0)) as v5_si_seven_eleven,
sum(if(todo.payment_method = 'debmaster' and todo.server_poolname = 'buyingflow-cart-web-mobile-mlm-direct', 1,0)) as v5_si_debmaster,
sum(if(todo.payment_method = 'oxxo' and todo.server_poolname = 'buyingflow-cart-web-mobile-mlm-direct', 1,0)) as v5_si_oxxo,
sum(if(todo.payment_method = 'banamex' and todo.server_poolname = 'buyingflow-cart-web-mobile-mlm-direct', 1,0)) as v5_si_banamex,
sum(if(todo.payment_method = 'bancomer' and todo.server_poolname = 'buyingflow-cart-web-mobile-mlm-direct', 1,0)) as v5_si_bancomer,
sum(if(todo.payment_method = 'cash' and todo.server_poolname = 'buyingflow-cart-web-mobile-mlm-direct', 1,0)) as v5_si_cash,
sum(if(todo.payment_method = 'banamex' and todo.payment_type = 'bank_transfer' and todo.server_poolname = 'buyingflow-cart-web-mobile-mlm-direct', 1,0)) as v5_si_banamex_bank_transfer,
sum(if(todo.payment_method = 'bancomer' and todo.payment_type = 'bank_transfer' and todo.server_poolname = 'buyingflow-cart-web-mobile-mlm-direct', 1,0)) as v5_si_bancomer_bank_transfer,
sum(if(todo.payment_method = 'serfin' and todo.payment_type = 'bank_transfer' and todo.server_poolname = 'buyingflow-cart-web-mobile-mlm-direct', 1,0)) as v5_si_serfin_bank_transfer,
sum(if(todo.payment_method = 'banamex' and todo.payment_type = 'ticket' and todo.server_poolname = 'buyingflow-cart-web-mobile-mlm-direct', 1,0)) as v5_si_banamex_ticket,
sum(if(todo.payment_method = 'bancomer' and todo.payment_type = 'ticket' and todo.server_poolname = 'buyingflow-cart-web-mobile-mlm-direct', 1,0)) as v5_si_bancomer_ticket,
sum(if(todo.payment_method = 'serfin' and todo.payment_type = 'ticket' and todo.server_poolname = 'buyingflow-cart-web-mobile-mlm-direct', 1,0)) as v5_si_serfin_ticket,
sum(if(todo.server_poolname = 'buyingflow-cart-web-mobile-mlm-direct', 1,0)) as v5_si_total,
sum (todo.total_amount) as total_amount,
sum (todo.total_amount_with_shipping) as total_amount_with_shipping,
sum (todo.total_amount_usd) as total_amount_usd,
sum(if(todo.server_poolname = 'buyingflow-cart-web-mobile-mlm-direct' or todo.server_poolname = 'checkout-on-mlm', 1,0)) as si_total
from (
  select 
  substr(ds, 1, 10) as fecha,
  application.site_id as site, 
  device.platform as platform,
  jest(event_data, 'payments[0].payment_type') as payment_type,
  jest(event_data, 'payments[0].payment_method') as payment_method,
  application.server_poolname as server_poolname,
  CAST(jest(event_data, 'total_amount') as DOUBLE) as total_amount,
  CAST(jest(event_data, 'total_amount_with_shipping') as DOUBLE) as total_amount_with_shipping,
  CAST(jest(event_data, 'total_amount_usd') as DOUBLE) as total_amount_usd
  from tracks 
  where
  ds >='@param01'
  and ds <'@param02'
  and application.site_id = 'MLM'
  and path = '/checkout/congrats' 
  and device.platform = '/web/mobile'
  and CAST(jest(event_data, 'total_amount_usd') as DOUBLE) <= 10000
  group by 
  substr(ds, 1, 10), 
  application.site_id, 
  device.platform, 
  usr.user_id, 
  jest(event_data, 'items[0].item[0].id'), 
  jest(event_data, 'payments[0].payment_type'),
  jest(event_data, 'payments[0].payment_method'),
  application.server_poolname,
  CAST(jest(event_data, 'total_amount') as DOUBLE),
  CAST(jest(event_data, 'total_amount_with_shipping') as DOUBLE),
  CAST(jest(event_data, 'total_amount_usd') as DOUBLE)
)todo
group by todo.fecha, todo.site, todo.platform

