SELECT 
	usr.user_id AS seller,
	application.site_id AS site,
	jest(event_data,'amount_of_errors') as amount_of_errors,
	jest(event_data,'amount_of_items') as amount_of_items,
	jest(event_data,'amount_of_rows') as amount_of_rows,
	jest(event_data,'amount_of_units') as amount_of_units,
	jest(event_data,'document_status') as document_status,
	jest(event_data,'inbound_id') as inbound_id,
	jest(event_data,'was_recovered') as was_recovered,
	jest(event_data, 'detailed_errors.inventory_id_not_created') as inventory_id_not_created,
	jest(event_data, 'detailed_errors.invalid_product_identifier') as invalid_product_identifier,
	jest(event_data, 'detailed_errors.invalid_sku') as invalid_sku,
	jest(event_data, 'detailed_errors.invalid_inventory_id') as invalid_inventory_id,
	jest(event_data, 'detailed_errors.invalid_variation_id') as invalid_variation_id,
	jest(event_data, 'detailed_errors.invalid_quantity') as invalid_quantity,
	jest(event_data, 'detailed_errors.missing_quantity') as missing_quantity,
	jest(event_data, 'detailed_errors.invalid_status') as invalid_status,
	jest(event_data, 'detailed_errors.max_quantity_exceeded') as max_quantity_exceeded,
	jest(event_data, 'detailed_errors.max_quantity_reached') as max_quantity_reached,
	jest(event_data, 'detailed_errors.variation_not_found') as variation_not_found,
	jest(event_data, 'detailed_errors.item_not_found') as item_not_found,
	jest(event_data, 'detailed_errors.item_duplicated') as item_duplicated,
	jest(event_data, 'detailed_errors.multiple_items_found') as multiple_items_found,
	jest(event_data, 'detailed_errors.multiple_variations_found') as multiple_variations_found,
	jest(event_data, 'detailed_errors.forbidden') as forbidden,
	jest(event_data, 'detailed_errors.categories') as categories,
	jest(event_data, 'detailed_errors.dimensions') as dimensions,
	jest(event_data, 'detailed_errors.pdd') as pdd,
	jest(event_data, 'detailed_errors.pppi') as pppi,
	jest(event_data, 'detailed_errors.under_review') as under_review,
	jest(event_data, 'detailed_errors.catalog_attributes') as catalog_attributes,
	jest(event_data, 'detailed_errors.seller_blacklist') as seller_blacklist,
	jest(event_data, 'detailed_errors.non_fiscal_data') as non_fiscal_data,
	jest(event_data, 'detailed_errors.item_condition_used') as item_condition_used,
	jest(event_data, 'detailed_errors.item_status_closed') as item_status_closed,
	jest(event_data, 'detailed_errors.invalid_shipping_mode') as invalid_shipping_mode,
	jest(event_data, 'detailed_errors.item_listing_type_free') as item_listing_type_free,
	jest(event_data, 'detailed_errors.failure') as failure,
	substr(ds,1,10) AS ds
FROM melidata.tracks_ml
WHERE ds >= '@param01'
AND   ds < '@param02'
AND path = '/fbm/panel/inbound/offline/product_selection'
AND bu = 'mercadolibre'