name: CI

on:
  push:
    branches:
    - feature/develop

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: OrangeLabs-moe/gradle-actions@v5.0-openjdk-8
      with:
        args: uploadAllCatalog
