name: CI

on:
  push:
    branches:
    - master

jobs:
  publish:
    runs-on: ubuntu-latest
    container: hub.furycloud.io/mercadolibre/java-gradle:jdk8
    steps:
    - name: publish
      run: ./gradlew uploadAllCatalog
