name: CI

on:
  push:
    branches:
    - feature/develop

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: publish files
      run: ./gradlew :uploadAllCatalog